name: .NET

on:
  pull_request:
     branches-ignore:
        - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Bump versions
      uses: SiqiLu/dotnet-bump-version@master
      with:
        version_files: "**/*.csproj"
        github_token: ${{ secrets.GH_TOKEN }}

    - name: Commit version changes
      run: |
        git config --global user.name 'farpetrad'
        git config --global user.email 'farpetrad@gmail.com'
        git commit -am "Version bumped"
        git push
