name: Bump version after PR

on:
    pull_request:
        branches: 
         - master
        types: [closed]

jobs:
    handleMerge:
        if: ${{ github.event.pull_request.merged }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Bump versions
              uses: SiqiLu/dotnet-bump-version@master
              with:
                version_files: "**/*.csproj"
                github_token: ${{ secrets.GH_TOKEN }}

            - name: Commit version changes
              run: |
                git config --global user.name 'farpetrad'
                git config --global user.email 'farpetrad@gmail.com'
                git commit -am "Version bumped [skip actions]"
                git push
