name: OpenPR

on:
  push:
    branches-ignore:
        - master  
  pull_request:
     branches-ignore:
        - master  
     types: [opened]

jobs:
    update-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Bump version and push tag
              id: bump-and-tag
              uses: anothrNick/github-tag-action@1.36.0
              env:
                DEFAULT_BUMP: patch
                GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
                WITH_V: true
                DRY_RUN: true 
            - name: manipulate
              run: ::set-output name=version::${steps.bump-and-tag.outputs.new_tag#*\v}
            - name: output
              id: vars
              run: echo "the value = ${{ {steps.vars.version }} "
            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal

           