name: OpenPR

on:
  push:
    branches-ignore:
        - master  
  pull_request:
     branches-ignore:
        - master  
     types: [opened]

jobs:
    update-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Bump version and push tag
              id: bump-and-tag
              uses: anothrNick/github-tag-action@1.36.0
              env:
                DEFAULT_BUMP: patch
                GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
                WITH_V: true

            - name: Set Versions
              uses: actions/github-script@v4
              id: set_version
              with:
                script: |
                  const tag = context.ref.substring(10)
                  const no_v = tag.replace('v', '')
                  const dash_index = no_v.lastIndexOf('-')
                  const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
                  core.setOutput('tag', tag)
                  core.setOutput('no-v', no_v)
                  core.setOutput('no-dash', no_dash)
            
            - name: output
              id: vars
              run: echo ${{ steps.set_version.outputs.no_v }}

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal

           