name: pull-request
on: 
  pull_request

jobs:
    update-version:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 6.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Bump version and push tag
              id: bump-and-tag
              uses: anothrNick/github-tag-action@1.36.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
                WITH_V: true

            - id: get-id
              uses: actions/github-script@0.9.0
              with:
                script: |
                  const id = steps.bump-and-tag.outputs.new_tag.split('v')[1]
                  core.setOutput('id', id)
                
            - name: output
              id: tag-and-version
              run: echo "Output tag = ${{ steps.bump-and-tag.outputs.new_tag:11  }} parsed = ${{ steps.get-id.outputs.id }}"

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal

           