name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET}}        
          
      - name: Restore dependencies
        run: dotnet restore
      - name: Build it
        run: dotnet build -c Release -o Out
      - name: Move to Project
        run: cd SplinterLandsAPI
      - name: Pack it up
        run: dotnet pack -c Release -o Out

      - name: Push generated package to Nuget
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET }} --skip-duplicate
