name: Publish release to nuget

on:
    push:
      branches: 
       - master

jobs:
  Nuget:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup .NET Core 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Bump version and push tag
        id: bump-and-tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          WITH_V: true
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build it
        run: dotnet build -c Release --no-restore -p:Version=${{ steps.bump-and-tag.outputs.new_tag }}

      - name: Publish SplinterLandsAPI
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: SplinterLandsAPI/SplinterLandsAPI.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish SplinterLands.DTOs
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: SplinterLands.DTOs/SplinterLands.DTOs.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}